# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
    - develop
    - cibuild # Dedicated branch for testing ci and build script

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: '[1-1] Install .NET SDK 10.0'
  inputs:
    packageType: 'sdk'
    version: '10.0.x'
- task: DotNetCoreCLI@2
  displayName: '[1-2] Restore Nuget Pacakges'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
# Run tests first
- task: DotNetCoreCLI@2
  displayName: '[2-1] Run Tests'
  inputs:
    command: 'test'
    projects: '**/*.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger="console;verbosity=detailed" --collect:"XPlat Code Coverage" --settings:"$(Build.SourcesDirectory)/mstest.runsettings"'
- task: PublishCodeCoverageResults@2
  displayName: '[2-2] Publish Code Coverage Report'
  inputs:
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
# Publish nightly artifacts
- task: PowerShell@2
  displayName: '[3] Build Artifacts'
  inputs:
    filePath: '$(Build.SourcesDirectory)/BinaryPublish.ps1'
    arguments: '-nightly -noclean'
    pwsh: true
- task: PublishPipelineArtifact@1
  displayName: '[4-1] Upload nightly artifact (runtime-dependent)'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/Publish/PEBakery-nightly-rt.7z'
    artifact: 'nightly-rt'
    publishLocation: 'pipeline'
- task: PublishPipelineArtifact@1
  displayName: '[4-2] Upload nightly artifact (self-contained x64)'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/Publish/PEBakery-nightly-sc_x64.7z'
    artifact: 'nightly-sc_x64'
    publishLocation: 'pipeline'
- task: PublishPipelineArtifact@1
  displayName: '[4-3] Upload nightly artifact (self-contained arm64)'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/Publish/PEBakery-nightly-sc_arm64.7z'
    artifact: 'nightly-sc_arm64'
    publishLocation: 'pipeline'

# https://stackoverflow.com/questions/64592534/publish-a-pipeline-azure-devops-code-coverage-report
# https://www.gustavwengel.dk/optimize-dotnet-piplines-azure
