[Main]
Title=BranchGeneral
Author=ied206
Description=UnitTest
Version=001
Level=5
Selected=True
Mandatory=False

[Variables]
InlineMacro=Set,%^RET%,%^SIPARAM_1%
SectionMacro=Run,%ScriptFile%,SectionMacroImpl
CondMacro01=Run,%ScriptFile%,CondMacroImpl01
CondMacro02=Run,%ScriptFile%,CondMacroImpl02
PhoenixMacro=Run,%ScriptFile%,PhoenixMacroImpl
SetLocalParamsMacro=Run,%ScriptFile%,SetLocalParamsMacroImpl

[SectionMacroImpl]
Set,%^RET%,%^SIPARAM_1%

[CondMacroImpl01]
Set,%^RET%,0
If,%^SIPARAM_1%,Equal,True,Begin
  Set,%^RET%,T
End
Else,Begin
  Set,%^RET%,F
End

[CondMacroImpl02]
Set,%^RET%,0
If,%^SIPARAM_1%,Equal,True,Set,%^RET%,F
Else,Set,%^RET%,F
Set,%^RET%,T

[PhoenixMacroImpl]
System,SetLocal
Set,%^RET%,F
If,%^SIPARAM_1%,Equal,"",Exit,"Syntax Error"
If,%^SIPARAM_2%,Equal,"",Exit,"Syntax Error"
If,%^SIPARAM_3%,Equal,"",Exit,"Syntax Error"
GetParam,1,%A%
GetParam,2,%B%
GetParam,3,%C%
If,%^SIPARAM_1%,Equal,True,Begin
  If,%^SIPARAM_2%,Equal,0,Set,%^RET%,0
  Else,If,%^SIPARAM_2%,Equal,1,Set,%^RET%,1
  Else,If,%^SIPARAM_2%,Equal,2,Set,%^RET%,2
  Else,If,%^SIPARAM_2%,Equal,3,Set,%^RET%,3
  Else,Exit,"Syntax Error"
  
  If,%^SIPARAM_3%,Equal,T,Set,%^RET%,A
  Else,If,%^SIPARAM_3%,Equal,F,Set,%^RET%,B
  // The comment between If and Else had crashed CodeParser.FoldBranchCodeBlock() method in the past. 
  Else,Halt,"Syntax Error"
End
Else,Begin
  If,%^SIPARAM_3%,Equal,T,Set,%^RET%,X
  Else,If,%^SIPARAM_3%,Equal,F,Set,%^RET%,Y
  // The bug was reported by @homes32, and investigated and fixed by @ied206.
  Else,Halt,"Syntax Error"
End
Set,%^RET%,T
System,EndLocal

[SetLocalParamsMacroImpl]
System,SetLocal
GetParam,1,%A%
GetParam,2,%B%
GetParam,3,%C%
GetParam,4,%D%
If,%D%,Equal,"A/B/C",Set,%^RET%,"T"
System,EndLocal

[Process-InlineMacro]
AddVariables,%ScriptFile%,Variables
Set,%^RET%,F
InlineMacro,T

[Process-SectionMacro]
AddVariables,%ScriptFile%,Variables
Set,%^RET%,F
SectionMacro,T

[Process-CondMacro01]
AddVariables,%ScriptFile%,Variables
Set,%^RET%,F
CondMacro01,True

[Process-CondMacro02]
AddVariables,%ScriptFile%,Variables
Set,%^RET%,F
CondMacro02,True

[Process-PhoenixMacro]
AddVariables,%ScriptFile%,Variables
Set,%^RET%,F
PhoenixMacro,True,3,T

[Process-SetLocalParamsMacro]
AddVariables,%ScriptFile%,Variables
Set,%A%,"A"
Set,%B%,"B"
Set,%C%,"C"
Set,%^RET%,"F"
SetLocalParamsMacro,"X","Y","Z","%A%/%B%/%C%"
