//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEBakery.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PEBakery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   20180119과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @using System.Collections.Generic;
        ///@using PEBakery.Core;
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ko&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///        &lt;!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags --&gt;
        ///
        ///        &lt;title&gt;@Model.BuildName&lt;/title&gt;
        ///
        ///        &lt;!-- Bootstrap CSS --&gt;
        ///        &lt;link r[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BuildLogHtmlTemplate {
            get {
                return ResourceManager.GetString("BuildLogHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   92과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EngineVersion {
            get {
                return ResourceManager.GetString("EngineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unless specified, PEBakery is licensed under GPLv3 or any
        ///later version with additional permission.
        ///
        ///Some parts of PEBakery is licensed under various license,
        ///specified on a per-file basis or LICENSE file placed in
        ///a subdirectory.
        ///-----------------------------------------------------------
        ///Copyright (C) 2016-2018 Hajin Jang
        ///
        ///PEBakery is free software: you can redistribute it and/or
        ///modify it under the terms of the GNU General Public License
        ///as published by the Free Software Foundation, either
        ///ve[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LicenseSimple {
            get {
                return ResourceManager.GetString("LicenseSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0.9.2 beta2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringVersion {
            get {
                return ResourceManager.GetString("StringVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @using System.Collections.Generic;
        ///@using PEBakery.Core;
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ko&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///        &lt;!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags --&gt;
        ///
        ///        &lt;title&gt;PEBakery System Log&lt;/title&gt;
        ///
        ///        &lt;!-- Bootstrap CSS --&gt;
        ///        &lt;lin[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SystemLogHtmlTemplate {
            get {
                return ResourceManager.GetString("SystemLogHtmlTemplate", resourceCulture);
            }
        }
    }
}
