[Main]
Title=ControlGeneral
Author=ied206
Description=UnitTest
Version=001
Level=5
Selected=True
Mandatory=False

[TestVars]
%A%=1
%B%=2
%C%=3

[Process-GetParam00]
Run,%ScriptFile%,GetParam,0,""

[Process-GetParam01]
Run,%ScriptFile%,GetParam,1,"P1"

[Process-GetParam09]
Run,%ScriptFile%,GetParam,9,"P9"

[Process-GetParam12]
Run,%ScriptFile%,GetParam,12,"P12"

[Process-GetParam16]
Run,%ScriptFile%,GetParam,16,"P16"

[Process-GetParam18]
Run,%ScriptFile%,GetParam,18,""

[GetParam]
Set,%Dest%,F
Set,%Index%,#1
Run,%ScriptFile%,ReadParam,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16
If,%Result%,Equal,#2,Set,%Dest%,T

[ReadParam]
GetParam,%Index%,%Result%
