[Main]
Title=ControlGeneral
Author=ied206
Description=UnitTest
Version=001
Level=5
Selected=True
Mandatory=False

[TestVars]
%A%=1
%B%=2
%C%=3
InlineMacro=Set,%^RET%,T

[TestMacro]
SectionMacro=Run,%ScriptFile%,SectionMacroImpl
InlineMacro=Set,%^RET%,%^SIPARAM_1%

[SectionMacroImpl]
Set,%^RET%,%^SIPARAM_1%

[Process-SectionMacro-Global]
AddVariables,%ScriptFile%,TestMacro,GLOBAL
Set,%^RET%,F
SectionMacro,T

[Process-SectionMacro-Local]
AddVariables,%ScriptFile%,TestMacro
Set,%^RET%,F
SectionMacro,T

[Process-InlineMacro-Global]
AddVariables,%ScriptFile%,TestMacro,GLOBAL
Set,%^RET%,F
InlineMacro,T

[Process-InlineMacro-Local]
AddVariables,%ScriptFile%,TestMacro
Set,%^RET%,F
InlineMacro,T

[Process-GetParam00]
Run,%ScriptFile%,GetParam,0,""

[Process-GetParam01]
Run,%ScriptFile%,GetParam,1,"P1"

[Process-GetParam09]
Run,%ScriptFile%,GetParam,9,"P9"

[Process-GetParam12]
Run,%ScriptFile%,GetParam,12,"P12"

[Process-GetParam16]
Run,%ScriptFile%,GetParam,16,"P16"

[Process-GetParam18]
Run,%ScriptFile%,GetParam,18,""

[GetParam]
Set,%Dest%,F
Set,%Index%,%^SIPARAM_1%
Run,%ScriptFile%,ReadParam,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16
If,%Result%,Equal,%^SIPARAM_2%,Set,%Dest%,T

[ReadParam]
GetParam,%Index%,%Result%

[Process-Exit01]
Set,%^RET%,T
Exit,"%%^RET%% must be T"
Set,%^RET%,F

[Process-Exit02]
System,SetLocal
Set,%^RET%,T
Exit,"%%^RET%% must be T"
Set,%^RET%,F

[Process-Return01]
Set,%^RET%,INIT
Run,%ScriptFile%,"Process-SubReturn-NoValue"
Set,%Dest%,"%Dest%T"

[Process-Return02]
Set,%^RET%,INIT
Run,%ScriptFile%,"Process-SubReturn-NoValue",True
Set,%Dest%,"%Dest%T"

[Process-Return03]
Set,%^RET%,INIT
Run,%ScriptFile%,"Process-SubReturn-WithValue"
Set,%Dest%,"%Dest%T"

[Process-Return04]
Set,%^RET%,INIT
Run,%ScriptFile%,"Process-SubReturn-WithValue",True
Set,%Dest%,"%Dest%T"

[Process-SubReturn-NoValue]
Set,%Dest%,T
Set,%^RET%,SUB
Return
Set,%Dest%,F

[Process-SubReturn-WithValue]
Set,%Dest%,T
Set,%^RET%,SUB
Return,%^SIPARAM_1%
Set,%Dest%,F

[Process-Halt-Simple]
Set,%^RET%,T
Halt
Set,%^RET%,F

[Process-Halt-InIf]
Set,%i%,True
If,%i%,Equal,True,Begin
  Set,%^RET%,T
  Halt
  Set,%^RET%,F
End

[Process-Halt-InWhile]
Set,%i%,0
While,%i%,Smaller,4,Begin
  If,%i%,Equal,2,Halt
  Math,Add,%i%,%i%,1
  Set,%^RET%,"%^RET%A"
 End
