/*
    Copyright (C) 2018 Hajin Jang
 
    MIT License

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
*/

using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.IO;
using System.Text;

namespace PEBakery.Helper.Tests
{
    [TestClass]
    public class HtmlHelperTests
    {
        #region GenerateDataUri
        [TestMethod]
        [TestCategory("Helper")]
        [TestCategory("HtmlHelper")]
        public void GenerateDataUriByte()
        {
            string srcDir = Path.Combine(TestSetup.SampleDir, "HtmlHelper");
            string srcFile = Path.Combine(srcDir, "Banner.png");
            string compFile = Path.Combine(srcDir, "BannerPngDataUri.txt");

            string destDataUri;
            using (FileStream fs = new FileStream(srcFile, FileMode.Open, FileAccess.Read))
            {
                byte[] buffer = new byte[fs.Length];
                fs.Read(buffer, 0, buffer.Length);
                destDataUri = HtmlHelper.GenerateDataUri(HtmlHelper.MimeType.Png, buffer);
            }

            using (StreamReader r = new StreamReader(compFile, Encoding.UTF8, false))
            {
                string compDataUri = r.ReadToEnd();
                Assert.IsTrue(destDataUri.Equals(compDataUri, StringComparison.Ordinal));
            }
        }

        [TestMethod]
        [TestCategory("Helper")]
        [TestCategory("HtmlHelper")]
        public void GenerateDataUriStr()
        {
            string srcDir = Path.Combine(TestSetup.SampleDir, "HtmlHelper");
            string srcFile = Path.Combine(srcDir, "BannerDist.svg");
            // CompFile generated by https://dopiaza.org/tools/datauri/index.php
            // Unable to test urlencoded data uri, because implementations results different results.
            string compBase64File = Path.Combine(srcDir, "BannerDistSvgBase64DataUri.txt");

            string base64DataUri;
            using (StreamReader r = new StreamReader(srcFile, Encoding.UTF8, false))
            {
                string srcFileData = r.ReadToEnd();
                base64DataUri = HtmlHelper.GenerateDataUri(HtmlHelper.MimeType.Svg, srcFileData, true);
            }

            using (StreamReader r = new StreamReader(compBase64File, Encoding.UTF8, false))
            {
                string compDataUri = r.ReadToEnd();
                Assert.IsTrue(base64DataUri.Equals(compDataUri, StringComparison.Ordinal));
            }
        }
        #endregion
    }
}
