[Main]
Title=DirDelete
Type=Plugin
Author=ied206
Description=UnitTest of DirDelete
Credits=
Version=001
Level=05
Selected=True
Mandatory=False
NoWarning=False

[HelpMessage]
DirDelete,<DirPath>
[FAST] optional command deprecated
Wildcard supported in <DirPath>
This command only deletes directory, not file

[Process]
Echo,"Testing %ScriptTitle% ..."
// Test Wildcard Mode
DirCopy,%TestSrc%\01_DirDelete,%TestDest%\01_DirDelete\Wildcard
DirDelete,%TestDest%\01_DirDelete\Wild*
// Test Normal Mode
DirCopy,%TestSrc%\01_DirDelete,%TestDest%\01_DirDelete\Normal
DirDelete,%TestDest%\01_DirDelete\Normal
