[Main]
Title=FileCopy
Type=Plugin
Author=ied206
Description=UnitTest of FileCopy
Credits=
Version=001
Level=05
Selected=True
Mandatory=False
NoWarning=False

[HelpMessage]
FileCopy,<SrcFile>,<DestPath>[,PRESERVE][,NOWARN][,NOREC]
Wildcard supported in <SrcFile>

[Process]
Echo,"Testing %ScriptTitle% ..."
FileCopy,%TestSrc%\01_FileCopy\Hello.txt,%TestDest%\01_FileCopy\World.txt
FileCopy,%TestSrc%\01_FileCopy\World*.txt,%TestDest%\01_FileCopy
