<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
      <TargetFramework>net10.0-windows</TargetFramework>
      <Configurations>Debug;Release</Configurations>
      <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
      <Nullable>enable</Nullable>
      <Version>1.1.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PEBakery.Helper\PEBakery.Helper.csproj" />
  </ItemGroup>
</Project>