[Main]
Title=BranchGeneral
Author=ied206
Description=UnitTest
Version=001
Level=5
Selected=True
Mandatory=False

[Process-Run]
Set,%Dest%,F
Run,%ScriptFile%,SetTrue

[Process-Exec]
Set,%Dest%,F
Set,%ExecVar%,F
Exec,%ScriptDir%\Exec.script,SetTrue
Set,%Dest%,#r

[SetTrue]
Set,%Dest%,T

[Process-Loop01]
Set,%Dest%,NIL
Loop,%ScriptFile%,LoopTest,1,3,Z

[Process-Loop02]
Set,%Dest%,""
Loop,%ScriptFile%,LoopBreak,1,4,Z,3

[Process-LoopLetter01]
Set,%Dest%,NIL
LoopLetter,%ScriptFile%,LoopTest,C,E,Z

[Process-LoopLetter02]
Set,%Dest%,""
LoopLetter,%ScriptFile%,LoopBreak,C,F,Z,E

[LoopTest]
List,Append,%Dest%,#c
List,Append,%Dest%,#1

[LoopBreak]
List,Append,%Dest%,#c
List,Append,%Dest%,#1
If,#c,Equal,#2,Loop,BREAK

[Process-IfBeginEnd]
Set,%Dest%,F
Set,#r,True
If,#r,Equal,True,Begin
    Set,%Dest%,T
End
