[Main]
Title=BranchGeneral
Author=ied206
Description=UnitTest
Version=001
Level=5
Selected=True
Mandatory=False

[Process-Run]
Set,%Dest%,F
Run,%ScriptFile%,SetTrue

[Process-Run-InParam]
Set,%Dest%,F
Run,%ScriptFile%,SetParam,T

[Process-RunEx-OutParam]
Set,%Dest%,F
RunEx,%ScriptFile%,SetOutParam,In=T,Out=%Dest%

[Process-RunEx-OutParam-Error]
Set,%Dest%,F
RunEx,%ScriptFile%,SetOutParam,In=T

[Process-Exec]
Set,%Dest%,F
Set,%ExecVar%,F
Exec,%ScriptDir%\Exec.script,SetTrue
Set,%Dest%,#r

[SetTrue]
Set,%Dest%,T

[SetParam]
Set,%Dest%,#1

[SetOutParam]
Set,#o1,#1

[Process-Loop01]
Set,%Dest%,NIL
Loop,%ScriptFile%,LoopTest,1,3,Z

[Process-Loop02]
Set,%Dest%,""
Loop,%ScriptFile%,LoopBreak,1,4,Z,3

[Process-LoopEx-OutParam]
Set,%Dest%,NIL
LoopEx,%ScriptFile%,LoopOutParam,1,3,In=Z,Out=%Dest%

[Process-LoopEx-OutParam-Error]
Set,%Dest%,""
LoopEx,%ScriptFile%,LoopOutParam,1,3,In=Z

[Process-LoopCompat01]
Set,%Dest%,NIL
Loop,%ScriptFile%,LoopTest,C,E,Z

[Process-LoopCompat02]
Set,%Dest%,""
Loop,%ScriptFile%,LoopBreak,C,F,Z,E

[Process-LoopLetter01]
Set,%Dest%,NIL
LoopLetter,%ScriptFile%,LoopTest,C,E,Z

[Process-LoopLetter02]
Set,%Dest%,""
LoopLetter,%ScriptFile%,LoopBreak,C,F,Z,E

[Process-LoopLetterEx-OutParam]
Set,%Dest%,NIL
LoopLetterEx,%ScriptFile%,LoopOutParam,C,E,In=Z,Out=%Dest%

[Process-LoopLetterEx-OutParam-Error]
Set,%Dest%,""
LoopLetterEx,%ScriptFile%,LoopOutParam,C,E,In=Z

[LoopTest]
List,Append,%Dest%,#c
List,Append,%Dest%,#1

[LoopOutParam]
List,Append,#o1,#c
List,Append,#o1,#1

[LoopBreak]
List,Append,%Dest%,#c
List,Append,%Dest%,#1
If,#c,Equal,#2,Loop,BREAK

[Process-IfElse]
Set,%Dest%,F
Set,#r,False
If,#r,Equal,True,Begin
    Set,%Dest%,F
End
Else,Begin
	Set,%Dest%,T
End

[Process-IfElseChain]
Set,%Dest%,F
Set,#r,5
If,#r,Equal,1,Set,%Dest%,F
Else,If,#r,Equal,2,Set,%Dest%,F
Else,If,#r,Equal,3,Set,%Dest%,F
Else,If,#r,Equal,4,Set,%Dest%,F
Else,If,#r,Equal,5,Set,%Dest%,T

[Process-IfBeginEnd]
Set,%Dest%,F
Set,#r,True
If,#r,Equal,True,Begin
    Set,%Dest%,T
End


